# Generated by Django 3.0.6 on 2020-06-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20200604_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='first_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='addition',
            name='second_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='addition',
            name='total',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='division',
            name='first_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='division',
            name='second_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='division',
            name='total',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplication',
            name='first_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplication',
            name='second_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplication',
            name='total',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='subtraction',
            name='first_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='subtraction',
            name='second_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='subtraction',
            name='total',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
